Device Service review v2
edgexfoundry/device-uart pull request #6
Opened 2022-10-17 16:36 UTC by iain-anderson

Review of device-uart which is proposed to be adopted into edgexfoundry.
Process and criteria are set out at https://wiki.edgexfoundry.org/display/FA/Process+for+new+Device+Services

Note that if adopted we will be targeting a release based on Levski (EdgeX v2.3)
Previous review discussions here: #3

2023-02-04 07:13 UTC, cloudxxx8 reviewed
this PR looks good to me for v2.2.x release
do we need to upgrade to v2.3?

2023-02-04 07:13 UTC, cloudxxx8 commented on Dockerfile
> +RUN sed -e 's/dl-cdn[.]alpinelinux.org/nl.alpinelinux.org/g' -i~ /etc/apk/repositories
These three lines should also be removed

2023-02-14 16:52 UTC, lenny-intel commented
> do we need to upgrade to v2.3?

Yes, the target for initial release is 2.3.0

2023-02-22 19:57 UTC, lenny-intel requested changes

2023-05-18 10:27 UTC, iain-anderson commented
Service accepted into EdgeX as per TSC vote 3rd May 2023

2023-05-18 10:27 UTC, closed without merging